# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

sudo: true

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r gdata
  - ./travis-tool.sh install_r gplots
  - ./travis-tool.sh install_r testthat
  - ./travis-tool.sh install_bioc GenomicRanges
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
    - BIOC_USE_DEVEL="FALSE"
  - WARNINGS_ARE_ERRORS=0


notifications:
  email:
    on_success: change
    on_failure: change
